'use client';
import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // if (router.path === '/en') {
  //   return <En />;
  // }
    return (
    <html lang="en" dir={localStorage.getItem("lang") === "ar"? "rtl":"ltr"}>
      <body >{children}</body>
    </html>
  )
}
